example = '"конкатенация_!'
print (example)
print (example[0])
print (example[-1])
print (example[7:])
print (example[::-1])
print (example[1::2])
print()

print()
print()
print()
example = '"Топинамбур"'
print ("1  " + example)
print (("2 " + example + "'вкусный'   ")*5)
print ("3  " + example *2 + "   'вкусный'   "*3)
print ("4  " + example[0:3])
print ("5  " + example[-3])
print ("6  " + example[0:11:3])
print ("7  " + example[:11:3])
print ("8  " + example[3:])
print ("9  " + example[::-1])
print ("10 " + example[:2:-2])
print()